apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
  type: ClusterIP

