apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
  type: ClusterIP

